[package]
name = "timelapse_listener"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
image = "0.24"
decompress_image = { path = "../decompress_image" }
