[package]
name = "image_handling"
version = "0.1.0"
edition = "2024"

[dependencies]
v4l = "0.14"
image = "0.24"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3"
chrono = "0.4"
reqwest = { version = "0.13.1", features = ["blocking", "json"] }
